---
# tasks file for ansible-role-molecule-linux-windows

- name: Ensure all tasks based on the distribution are loaded
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
